### ISSUE TITLE
In readme.md "inkycal" should be "Inkycal"

### ISSUE THREAD

**Issue by emilyboda** [aceisace/inkycal_template#1]
I'm rusty on github, can't figure out how to make a PR for this.

Line 28 in the readme is:
`inkycal.add_module('/full/path/to/your/module.py')`

It needs to be:
`Inkycal.add_module('/full/path/to/your/module.py')`

**Comment by aceisace** [comment]
Thanks for pointing out the typo @emilyboda 😄  . This is now fixed [here](https://github.com/aceisace/inkycal_template/commit/350c3e1c2c2e0fb3689546e7e4efbca334b4b857)

I'll be closing this issue as it has been resolved. Should you feel a need to re-open this issue, please feel free to do so :)
